name: CI
on:
  workflow_dispatch: {}
jobs:
  test:
    if: ${{ github.actor == 'y-bonfire' }}
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Decode credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 -d > test/service_account.json

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test_ci
        env:
          GOOGLE_DRIVE_TEST_SPREADSHEET_ID: ${{ secrets.GOOGLE_DRIVE_TEST_SPREADSHEET_ID }}
          DST_GOOGLE_DRIVE_TEST_SPREADSHEET_ID: ${{ secrets.DST_GOOGLE_DRIVE_TEST_SPREADSHEET_ID }}

      - name: Run bundler-audit
        run: |
          bundle audit check --update